import type { Tier } from './types';

// Tier 1: Foundations. Written for someone who has never played a hand.
// UK English. Every term is defined the first time it appears.

export const tier1: Tier = {
  id: 'tier1',
  number: 1,
  title: 'Foundations',
  tagline: 'Start here',
  description:
    'The absolute basics. By the end you will know the cards, how a hand is played out, and the words people use at the table.',
  lessons: [
    {
      id: 't1-l1',
      title: 'The deck and hand rankings',
      minutes: 7,
      summary: 'What is in the deck and which five-card hands beat which.',
      blocks: [
        { type: 'p', text: 'Welcome to PokerPath. We will start from zero, so do not worry if you have never touched a deck of cards.' },
        { type: 'h', text: 'The deck' },
        { type: 'p', text: 'Texas Hold’em uses one standard 52-card deck. There are four suits: clubs, diamonds, hearts and spades. Each suit has 13 cards, running 2 up to 10, then Jack, Queen, King and Ace.' },
        { type: 'term', term: 'Suit', definition: 'One of the four families of cards: clubs, diamonds, hearts or spades. In Hold’em no suit is worth more than another.' },
        { type: 'p', text: 'The Ace is special: it is normally the highest card, but it can also act as the lowest card to make the smallest straight (we will meet straights below).' },
        { type: 'h', text: 'You always make the best five cards' },
        { type: 'p', text: 'No matter how many cards are in play, your hand is always your best five cards. The goal is to end up with a stronger five-card hand than your opponents, or to make them give up before the cards are shown.' },
        { type: 'h', text: 'The hand rankings, strongest to weakest' },
        { type: 'ordered', items: [
          'Royal flush: A, K, Q, J, 10 all of the same suit. The best possible hand.',
          'Straight flush: five cards in a row, all the same suit, for example 9-8-7-6-5 of hearts.',
          'Four of a kind: four cards of the same rank, for example four Kings.',
          'Full house: three of a kind plus a pair, for example three 8s and two 4s.',
          'Flush: any five cards of the same suit, not in a row.',
          'Straight: five cards in a row of mixed suits, for example 10-9-8-7-6.',
          'Three of a kind: three cards of the same rank.',
          'Two pair: two separate pairs, for example two Queens and two 5s.',
          'One pair: two cards of the same rank.',
          'High card: none of the above. Your highest card plays.',
        ] },
        { type: 'callout', tone: 'tip', text: 'A handy memory aid: the rarer a hand is, the stronger it is. Flushes and straights are uncommon, so they beat pairs, which happen all the time.' },
        { type: 'h', text: 'Breaking ties' },
        { type: 'p', text: 'If two players have the same type of hand, the higher cards win. Two players with one pair? The bigger pair wins. Same pair? Then the next highest card, called the kicker, decides it.' },
        { type: 'term', term: 'Kicker', definition: 'A side card that breaks a tie when two hands are otherwise equal. For example, A-A-K beats A-A-Q because the King kicker is higher than the Queen.' },
        { type: 'callout', tone: 'note', text: 'If hands are completely identical in rank, the pot is split evenly. Suits never break ties in Hold’em.' },
      ],
      quiz: [
        { id: 't1-l1-q1', prompt: 'How many cards are in a standard poker deck?', options: ['48', '52', '54', '60'], correctIndex: 1, explanation: 'A standard deck has 52 cards: 13 ranks in each of the four suits.' },
        { id: 't1-l1-q2', prompt: 'Which hand is stronger?', options: ['A flush', 'A straight', 'They are equal', 'Two pair'], correctIndex: 0, explanation: 'A flush (five of the same suit) beats a straight (five in a row of mixed suits).' },
        { id: 't1-l1-q3', prompt: 'Both players hold one pair of Aces. What decides the winner?', options: ['The suits of the Aces', 'The kicker (next highest card)', 'It is always a split pot', 'Whoever bet last'], correctIndex: 1, explanation: 'When the pair is the same, the highest side card (the kicker) breaks the tie. Suits never decide a winner.' },
        { id: 't1-l1-q4', prompt: 'What is the strongest possible hand?', options: ['Four of a kind', 'Full house', 'Royal flush', 'Straight flush'], correctIndex: 2, explanation: 'A royal flush (A-K-Q-J-10 of one suit) is the top of the straight flush category and the best hand in poker.' },
      ],
    },
    {
      id: 't1-l2',
      title: 'The table, the button and the blinds',
      minutes: 6,
      summary: 'Where everyone sits, who acts when, and the forced bets that start each hand.',
      blocks: [
        { type: 'p', text: 'Poker is played around a table, with each player taking turns to act. Two simple ideas control the whole rhythm of the game: the button and the blinds.' },
        { type: 'h', text: 'The button' },
        { type: 'term', term: 'Button', definition: 'A small disc that marks who is the nominal dealer for this hand. It moves one seat clockwise after every hand so everyone takes turns in each position.' },
        { type: 'p', text: 'The player on the button acts last on every round after the first. Acting last is a big advantage, because you get to see what everyone else does before you decide. We will return to this idea a lot.' },
        { type: 'h', text: 'The blinds' },
        { type: 'p', text: 'To make sure there is always something worth playing for, the two players to the left of the button must put money in before any cards are dealt. These forced bets are called the blinds.' },
        { type: 'term', term: 'Small blind', definition: 'The smaller forced bet, posted by the player directly to the left of the button.' },
        { type: 'term', term: 'Big blind', definition: 'The larger forced bet, posted by the next player along. It sets the basic bet size for the hand. Stakes are usually named after it, for example NL2 means a 2p big blind.' },
        { type: 'callout', tone: 'note', text: 'NL2, NL5, NL10 and so on are "No-Limit" cash games named by their big blind in pence. NL2 has a 2p big blind and a 1p small blind. These are the micro stakes where most people should start.' },
        { type: 'h', text: 'The order of play' },
        { type: 'p', text: 'Before the cards come out, action starts to the left of the big blind. On every later round, the small blind acts first and the button acts last. Play always moves clockwise.' },
        { type: 'callout', tone: 'tip', text: 'You do not need to memorise seat names yet. Just remember: the button is the best seat because it acts last, and the blinds are forced bets that the game rotates around.' },
      ],
      quiz: [
        { id: 't1-l2-q1', prompt: 'What does the button mark?', options: ['The strongest hand', 'The nominal dealer position for the hand', 'The minimum bet', 'The winner of the last hand'], correctIndex: 1, explanation: 'The button marks the nominal dealer. It rotates one seat clockwise each hand.' },
        { id: 't1-l2-q2', prompt: 'Who posts the big blind?', options: ['The player on the button', 'The player two seats to the left of the button', 'A randomly chosen player', 'Everyone at the table'], correctIndex: 1, explanation: 'The big blind is posted by the player two seats to the left of the button, just after the small blind.' },
        { id: 't1-l2-q3', prompt: 'Why is acting last (on the button) an advantage?', options: ['You get extra cards', 'You see what everyone else does before deciding', 'You pay smaller blinds', 'You win ties automatically'], correctIndex: 1, explanation: 'Information is power. Acting last lets you base your decision on what everyone else has already done.' },
        { id: 't1-l2-q4', prompt: 'In a game called NL5, how big is the big blind?', options: ['5 pounds', '5 pence', '50 pence', 'It varies each hand'], correctIndex: 1, explanation: 'No-Limit cash games are named by their big blind in pence, so NL5 has a 5p big blind.' },
      ],
    },
    {
      id: 't1-l3',
      title: 'Betting actions',
      minutes: 6,
      summary: 'Check, bet, call, raise, fold and all-in: the only moves you can make.',
      blocks: [
        { type: 'p', text: 'When it is your turn, you only ever have a small set of choices. Learn these six words and you can follow any game.' },
        { type: 'term', term: 'Check', definition: 'To pass the action to the next player without betting. You can only check if nobody has bet before you in this round.' },
        { type: 'term', term: 'Bet', definition: 'To put chips in when nobody else has bet yet this round. This forces others to call, raise or fold.' },
        { type: 'term', term: 'Call', definition: 'To match the current bet so you can carry on in the hand.' },
        { type: 'term', term: 'Raise', definition: 'To increase the current bet. Everyone after you must then match the new, larger amount to continue.' },
        { type: 'term', term: 'Fold', definition: 'To give up your hand and any chips you have already put in. You can no longer win this pot, but you lose nothing more.' },
        { type: 'term', term: 'All-in', definition: 'To put all of your remaining chips into the pot. You cannot bet more than you have on the table.' },
        { type: 'h', text: 'How a round flows' },
        { type: 'p', text: 'If nobody has bet, you can check or bet. If someone has bet, you can fold, call or raise. That is the whole decision tree on every street.' },
        { type: 'term', term: 'Pot', definition: 'The total pile of chips everyone is competing for in the current hand.' },
        { type: 'callout', tone: 'tip', text: 'Folding is not losing. Folding weak hands and saving your chips for strong spots is the single most profitable habit a beginner can build.' },
        { type: 'callout', tone: 'stakes', text: 'At micro stakes, the most common and costly mistake is calling too much. When in doubt between calling and folding, folding is usually the safer learning choice while you build judgement.' },
      ],
      quiz: [
        { id: 't1-l3-q1', prompt: 'Nobody has bet yet this round. Which actions are available to you?', options: ['Call or raise', 'Check or bet', 'Fold or call', 'Only all-in'], correctIndex: 1, explanation: 'With no bet in front of you, you may check (pass) or bet (put chips in). You cannot call when there is nothing to call.' },
        { id: 't1-l3-q2', prompt: 'An opponent bets and you want to stay in for the same amount. What is that called?', options: ['A raise', 'A check', 'A call', 'A fold'], correctIndex: 2, explanation: 'Matching the current bet to continue is a call.' },
        { id: 't1-l3-q3', prompt: 'What happens to chips you have already put in when you fold?', options: ['You get them back', 'They stay in the pot and you cannot win them', 'They go to the player on your left', 'They are returned next hand'], correctIndex: 1, explanation: 'Folded chips stay in the pot. You lose nothing more, but you can no longer win the hand.' },
        { id: 't1-l3-q4', prompt: 'What does going "all-in" mean?', options: ['Betting the size of the pot', 'Putting in all your remaining chips', 'Calling every bet to the river', 'Raising twice in a row'], correctIndex: 1, explanation: 'All-in means committing all the chips you have in front of you. You can never wager more than that.' },
      ],
    },
    {
      id: 't1-l4',
      title: 'The flow of a hand',
      minutes: 8,
      summary: 'Preflop, flop, turn, river and showdown, step by step.',
      blocks: [
        { type: 'p', text: 'Every hand of Hold’em follows the same four betting rounds, called streets. Cards are shared in the middle of the table for everyone to use.' },
        { type: 'term', term: 'Hole cards', definition: 'Your two private cards, dealt face down. Only you can see them.' },
        { type: 'term', term: 'Community cards', definition: 'The shared face-up cards in the middle. Everyone combines them with their hole cards to make a hand.' },
        { type: 'h', text: 'Preflop' },
        { type: 'p', text: 'Everyone is dealt two hole cards. The first round of betting happens before any community cards appear. This is your first decision: is this hand worth playing?' },
        { type: 'h', text: 'The flop' },
        { type: 'p', text: 'Three community cards are dealt face up at once. This is called the flop. A second round of betting follows. Now you can start to see how strong your hand really is.' },
        { type: 'h', text: 'The turn' },
        { type: 'p', text: 'A fourth community card is dealt, called the turn. Another round of betting follows. Bets here are usually larger because the pot has grown.' },
        { type: 'h', text: 'The river' },
        { type: 'p', text: 'A fifth and final community card is dealt, called the river. There is one last round of betting. No more cards will come, so your hand is now fixed.' },
        { type: 'h', text: 'Showdown' },
        { type: 'term', term: 'Showdown', definition: 'If two or more players are still in after the final bet, they reveal their hole cards and the best five-card hand wins the pot.' },
        { type: 'p', text: 'Remember, a hand can end at any point if everyone but one player folds. You do not need the best hand to win, only the last hand standing or the best at showdown.' },
        { type: 'callout', tone: 'note', text: 'Quick recap of the streets in order: preflop, flop (3 cards), turn (1 card), river (1 card), showdown.' },
      ],
      quiz: [
        { id: 't1-l4-q1', prompt: 'How many community cards are on the flop?', options: ['One', 'Two', 'Three', 'Five'], correctIndex: 2, explanation: 'The flop deals three community cards at once.' },
        { id: 't1-l4-q2', prompt: 'What is the correct order of the betting rounds?', options: ['Flop, preflop, turn, river', 'Preflop, flop, turn, river', 'Preflop, turn, flop, river', 'Flop, turn, river, preflop'], correctIndex: 1, explanation: 'The streets always run preflop, then flop, then turn, then river.' },
        { id: 't1-l4-q3', prompt: 'What are your two private cards called?', options: ['Community cards', 'Hole cards', 'The flop', 'Kickers'], correctIndex: 1, explanation: 'Your two face-down private cards are your hole cards.' },
        { id: 't1-l4-q4', prompt: 'Do you always need the best hand to win the pot?', options: ['Yes, always', 'No, everyone else can fold first', 'Only at showdown', 'Only preflop'], correctIndex: 1, explanation: 'If everyone else folds, you win without showing your cards. You only need the best hand when there is a showdown.' },
      ],
    },
    {
      id: 't1-l5',
      title: 'Etiquette and online tables',
      minutes: 5,
      summary: 'How to behave at the table and how online play differs from live.',
      blocks: [
        { type: 'p', text: 'Poker has a few simple courtesies that keep games friendly and fair. Most matter just as much online as they do in person.' },
        { type: 'h', text: 'Good habits' },
        { type: 'list', items: [
          'Act in turn. Wait for the players before you to decide.',
          'Be clear about your action. Say "call", "raise" or "fold" so there is no confusion.',
          'Do not reveal your cards while a hand is still being played.',
          'Keep a steady pace. Take your time on tough spots, but do not stall on easy ones.',
          'Be gracious whether you win or lose. Everyone has bad runs.',
        ] },
        { type: 'h', text: 'How online tables work' },
        { type: 'p', text: 'Online, the software handles the dealing, the button, the blinds and the pot automatically. You simply click buttons to fold, call, check or raise, often with a slider to choose your bet size.' },
        { type: 'term', term: 'Time bank', definition: 'A small reserve of extra seconds the software gives you for difficult decisions when your normal turn timer runs low.' },
        { type: 'term', term: 'Multi-tabling', definition: 'Playing more than one online table at the same time. Useful later on, but stick to a single table while you are learning.' },
        { type: 'callout', tone: 'tip', text: 'Many sites let you sit out, use a notes feature, and review your hand history afterwards. Reviewing your own hands is one of the fastest ways to improve.' },
        { type: 'callout', tone: 'warning', text: 'Never share your account or let someone else play your hands. It breaks the rules of every site and can get you banned.' },
      ],
      quiz: [
        { id: 't1-l5-q1', prompt: 'Why should you act in turn?', options: ['It is faster', 'Acting early gives away information and is unfair', 'It is required to win', 'So you can see more cards'], correctIndex: 1, explanation: 'Acting out of turn gives other players information they should not have yet and is considered poor etiquette.' },
        { id: 't1-l5-q2', prompt: 'What does a "time bank" give you?', options: ['Extra chips', 'Extra seconds for tough decisions', 'A free hand', 'A bigger blind'], correctIndex: 1, explanation: 'The time bank is a reserve of extra seconds for difficult spots when your normal timer is running out.' },
        { id: 't1-l5-q3', prompt: 'While you are still learning, how many tables should you play online?', options: ['As many as possible', 'Just one', 'At least four', 'It does not matter'], correctIndex: 1, explanation: 'Stick to a single table while learning so you can focus on each decision. Multi-tabling can come much later.' },
      ],
    },
  ],
  milestone: {
    id: 't1-milestone',
    title: 'Hand Ranking Challenge',
    description:
      'Put your knowledge of hand rankings to the test. You will see ten matchups and must pick the winning hand. Score 80% to complete Tier 1.',
    kind: 'hand-ranking',
    passFraction: 0.8,
    rounds: 10,
  },
};
